config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :items
  resources :photos

  resources :items do
    resources :bookings, only: [:create]
  end

  get '/preload' => 'bookings#preload'
  get '/preview' => 'bookings#preview'

  get '/your_rentals' => 'bookings#your_rentals'
  get '/your_reservations' => 'bookings#your_reservations'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :item_type, presence: true
  validates :item_name, presence: true, length: {maximum: 50}
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :item

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, :path => ":rails_root/public/photos/:id/:filename", :url => "/photos/:id/:filename"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :items
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :fullname, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def preload
		item = Item.find(params[:item_id])
		today = Date.today
		bookings = item.bookings.where("start_date >= ? OR end_date >= ?", today, today)

		render json: bookings
	end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
			conflict: is_conflict(start_date, end_date)
		}

    render json: output
  end

  def create
    item = Item.find(params[:item_id])
    if current_user == item.user
      redirect_to item, notice: "You can't reserve your own room!"
    else
      @booking = current_user.bookings.create(booking_params)
      redirect_to @booking.item, notice: "Your booking has been created!"
    end
  end

  def your_rentals
    @rentals = current_user.bookings
  end

  def your_reservations
    @items = current_user.items
  end

  private

  def is_conflict(start_date, end_date)
    item = Item.find(params[:item_id])

    check = item.bookings.where("? < start_date AND end_date < ?", start_date, end_date)
    check.size > 0? true : false
  end

    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :price, :total, :item_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @items = current_user.items
  end

  def show
    @photos = @item.photos
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save

      if params[:images]
        params[:images].each do |image|
          @item.photos.create(image: image)
        end
      end

      @photos = @item.photos
      redirect_to edit_item_path(@item)
      flash[:success] = "Item added!"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @item.user.id
      @photos = @item.photos
    else
      redirect_to root_path, notice: "You just don't do dat!"
    end
  end

  def update
    if @item.update(item_params)

      if params[:images]
        params[:images].each do |image|
          @item.photos.create(image: image)
        end
      end

    flash[:success] = "Item details updated."
    redirect_to edit_item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item deleted"
    redirect_to items_url
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:item_type, :item_name, :description, :price, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @items = Item.all
  end

  def search
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def show
    @photo = Photo.find(params[:id]);
  end

  def destroy
    @photo = Photo.find(params[:id])
    item = @photo.item

    @photo.destroy
    @photos = Photo.where(item_id: item.id)

    respond_to do |format|
      format.js
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@items = @user.items
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/_form.html.erb
<%= form_for ([@item, @item.bookings.new]) do |f| %>

    <div class="col-md-12 price_tag">
      <span>$<%= @item.price %></span>
      <span class="pull-right">Per Day</span>
    </div>
    <div class="col-md-6">
      <label>Rent from</label>
      <%= f.text_field :start_date, readonly: 'true', placeholder: 'Start Date', class: 'form-control' %>
    </div>
      <div class="col-md-6 clear-bottom">
        <label>To</label>
        <%= f.text_field :end_date, readonly: 'true', placeholder: 'End Date', class: 'form-control' %>
      </div>

      <%= f.hidden_field :item_id, value: @item.id %>
      <%= f.hidden_field :price, value: @item.price %>
      <%= f.hidden_field :total, id: 'booking_total' %>

      <h4><span id="message"></span></h4>

      <div id="preview" style="display: none">
        <table class="booking-table">
          <tbody>
            <tr>
              <td>Day(s)</td>
              <td><span id="booking_days"></span></td>
            </tr>
            <tr>
              <td>Total</td>
              <td><span id="booking_sum"></span></td>
            </tr>
          </tbody>
        </table>
      </div>
      <%= f.submit "Book Now", id: "btn_book", class: "btn btn-primary btn-block" %>



<% end %>

<script>

	function unavailable(date) {
		dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
		return [$.inArray(dmy, unavailableDates) == -1];
	}

	$(function() {

		unavailableDates = [];

		$.ajax({
			url: '/preload',
			data: {'item_id': <%= @item.id %>},
			dataType: 'json',
			success: function(data) {

				$.each(data, function(arrID, arrValue) {
					for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
						unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
					}
				});

				$('#booking_start_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#booking_end_date').datepicker("option", "minDate", selected);
						$('#booking_end_date').attr('disabled', false);
					}
				});

				$('#booking_end_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#booking_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#booking_start_date').datepicker('getDate');
						var end_date = $('#booking_end_date').datepicker('getDate');
						var days = (end_date - start_date)/1000/60/60/24 + 1
            var input = {
              'start_date': start_date,
              'end_date': end_date,
              'item_id': <%= @item.id %>
            }

            $.ajax({
              url: "/preview",
              data: input,
              success: function(data) {

                if (data.conflict) {

                  $('#message').text("This date range is not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);

                } else {

                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = days * <%= @item.price %>
                  $('#booking_days').text(days);
                  $('#booking_sum').text(total);
                  $('#booking_total').val(total);
                }
              }
            });

          }
        });
      }
    });



  });
</script>

app/views/bookings/your_rentals.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="nav nav-pills nav-stacked">
			<li><%= link_to "Your Listings", items_path, class: "sidebar-link" %></li>
			<li><%= link_to "Your Reservations", your_reservations_path %></li>
      <li class="active"><%= link_to "Your Rentals", your_rentals_path, class: "sidebar-link" %></li>
    </ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Rentals
			</div>
			<div class="panel-body">

        <% @rentals.each do |rental| %>
					<div class="row">
						<div class="col-md-2">
							<%= rental.start_date.strftime('%v') %>
						</div>
						<div class="col-md-6">
							<%= link_to item_path(rental.item) do %>
								<%= image_tag rental.item.photos[0].image.url(:thumb) if rental.item.photos.length > 0 %>
							<% end %>
						</div>
						<div class="col-md-2">
              Rented from
              <%= link_to user_path(rental.item.user) do %>
								<%= rental.item.user.fullname %>
							<% end %>
						</div>
						<div class="col-md-2 right">
							<h4>$<%= rental.total %></h4>
						</div>
					</div>
					<hr>
				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/bookings/your_reservations.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="nav nav-pills nav-stacked">
			<li><%= link_to "Your Listings", items_path, class: "sidebar-link" %></li>
			<li class="active"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li><%= link_to "Your Rentals", your_rentals_path, class: "sidebar-link" %></li>
    </ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Reservations
			</div>
			<div class="panel-body">
        <% @items.each do |item| %>

					<% item.bookings.each do |booking| %>
					<div class="row">
						<div class="col-md-2">
							<%= booking.start_date.strftime('%v') %>
						</div>
						<div class="col-md-6">
							<%= link_to item_path(booking.item) do %>
								<%= image_tag booking.item.photos[0].image.url(:thumb) if booking.item.photos.length > 0 %>
							<% end %>
						</div>
						<div class="col-md-2">
              Reserved by
              <%= link_to user_path(booking.user) do %>
								<%= booking.user.fullname %>
							<% end %>
						</div>
						<div class="col-md-2 right">
							<h4>$<%= booking.total %></h4>
						</div>
					</div>
					<hr>
				<% end %>

        <% end %>

			</div>
		</div>
	</div>
</div>

app/views/items/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  Rent Your Item
  </div>
  <div class="panel-body">
    <div class="container">
      <%= form_for @item, :html => { multipart: true } do |f| %>

      <div class="row">
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Item Type</label>
            <%= f.select :item_type, [["Baking & Cooking", "Baking & Cooking"], ["Costumes", "Costumes"], ["Inflatables", "Inflatables"], ["Board & Card Games", "Board & Card Games"], ["Console Games", "Console Games"], ["Outdoors", "Outdoors"], ["Sports", "Sports"], ["Water Sports", "Water Sports"], ["Tech Gadgets", "Tech Gadgets"]],
            id: "item_type", prompt: "Select...", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <label>Item name</label>
            <%= f.text_field :item_name, placeholder: "Be clear and descriptive!", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <label>Description</label>
            <%= f.text_area :description, rows: 5, placeholder: "Share more about your item", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <label>Address</label>
            <%= f.text_field :address, placeholder: "What is your address?", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label>Daily Price</label>
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <%= f.text_field  :price, placeholder: "eg. $10", class: "form-control" %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <span class="btn btn-default btn-file">
                <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos
                <%= file_field_tag "images[]", type: :file, multiple: true %>
            </span>
          </div>
        </div>
      </div>

      <div id="photos"><%= render 'photos/list' %></div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="nav nav-pills nav-stacked">
			<li class="active"><%= link_to "Your Listings", items_path, class: "sidebar-link" %></li>
			<li><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li><%= link_to "Your Rentals", your_rentals_path, class: "sidebar-link" %></li>
    </ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">

				<% @items.each do |item| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag item.photos[0].image.url(:thumb) if item.photos.length > 0 %>
						</div>
						<div class="col-md-6">
							<h4><%= link_to item.item_name, item %></h4>
						</div>
						<div class="col-md-2 right">
							<%= link_to "Update", edit_item_path(item), class: "btn btn-primary" %>
						</div>
						<div class="col-md-2 right">
							<%= link_to "Delete", item, method: :delete, class: "btn btn-primary",
																						data: { confirm: "You sure?" } %>
						</div>
					</div>
				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/items/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <!-- Carousel -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

          <% if @photos %>
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
              <% end %>
            </ol>
          <% end %>

          <div class="carousel-inner" role="listbox">
            <% if @photos %>
              <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
              <% end %>
            <% end %>
          </div>

          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

<!-- Main Info -->
<div class="row">
  <div class="col-md-6 text-center">
    <h3><%= @item.item_name %></h3>
    <p>Description: <%= @item.description %>
    <p>Rate: $ <%= @item.price %> / day
    <p>Location: <%= @item.address %>
  </div>

<div class="col-md-4">
<!-- Reservation form -->
<%= render 'bookings/form' %>
</div>
</div>

<!-- Google Map -->
<div class="row">
  <div class="col-md-12">

    <div id="map"></div>

    <style>
      #map {
        width: 100%;
        height: 400px;
      }
    </style>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBd4kzMOzo3J98AZEB4zYHDnlDRLruwXWQ"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map');
        var mapOptions = {
          center: new google.maps.LatLng(<%= @item.latitude %>, <%= @item.longitude %>),
          zoom: 16,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions);

        var marker = new google.maps.Marker({
          position: new google.maps.LatLng(<%= @item.latitude %>, <%= @item.longitude %>),
          title: "Rent it!"
        });

        marker.setMap(map);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

  </div>
</div>


  </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentalist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    <link href='https://fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= render 'shared/message' %>

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <% @items.each do |item| %>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag item.photos[0].image.url(:medium) if item.photos.length > 0 %>
      </div>
      <div class="panel-body">
        <%= link_to item.item_name, item %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/pages/search.html.erb
<div id="wrapper">

	<div id="sidebar">
		<div id="widget" class="sticky">

		</div>
	</div>

	<div id="article">

		<div class="row">
			<%= search_form_for @search, url: search_path do |f| %>

				<div class="row">
					<div class="col-md-3">
						<%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
					</div>
					<div class="col-md-3">
						<%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
					</div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>Item Type</label>
              <%= f.select :item_type_gteq, [["Electronics", "Electronics"], ["Tools & Equipment", "Tools & Equipment"], ["Home Appliances", "Home Appliances"], ["Event Items", "Event Items"], ["Transport", "Transport"]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="row">
  					<%= f.submit "Search", class: "btn btn-primary" %>
  				</div>

  			<% end %>
  		</div>

  	</div>

  </div>

  <script>
  	$(function() {
  		$("#start_date").datepicker({
  			dateFormat: 'dd-mm-yy',
  			minDate: 0,
  			maxDate: '3m',
  			onSelect: function(selected) {
  				$('#end_date').datepicker("option", "minDate", selected);
  				$('#end_date').attr('disabled', false);
  			}
  		});

  		$("#end_date").datepicker({
  			dateFormat: 'dd-mm-yy',
  			minDate: 0,
  			maxDate: '3m',
  			onSelect: function(selected) {
  				$('#start_date').datepicker("option", "maxDate", selected);
  			}
  		});
  	})
  </script>

app/views/photos/_list.html.erb
<% if @photos %>

	<div class="row">
		<% @photos.each do |photo| %>
			<div class="col-md-4">
				<div class="panel panel-default">
				  <div class="panel-heading preview">
				  	<%= image_tag photo.image.url() %>
				  </div>
				  <div class="panel-body">
				  	<span class="pull-right">
				  		<%= link_to photo, remote: true, :method => :delete, data: {confirm: "Are you sure?"} do %>
					  		<i class="fa fa-times fa-lg"></i>
				  		<% end %>
				  	</span>
				  </div>
				</div>
			</div>
		<% end %>
	</div>

<% end %>

app/views/photos/destroy.js.erb
console.log('refresh the photo list');

$('#photos').html("<%= j render 'photos/list' %>")

app/views/photos/show.html.erb
<h1>Hellow: <%= @photo %></h1>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>

<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'rentalist', root_url, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.fullname %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Your Listings", items_path %></li>
              <li><%= link_to "Your Reservations", your_reservations_path %></li>
              <li><%= link_to "Your Rentals", your_rentals_path %></li>
              <li><a href="#">Wish Lists</a></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Account Settings</a></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :get %></li>
            </ul>
          </li>

        <% end %>

        <li>
          <a href="#"><i class="fa fa-envelope-o"></i> Messages</a>
        </li>
        <li>
          <a href="/items/new"><i class="fa fa-rocket"></i> Rent Your Stuff</a>
        </li>
      </ul>

    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/users/show.html.erb
<div class="row">

	<div class="col-md-9">
		<h2><%= @user.fullname %></h2>
	</div>

	<h4>Listings (<%= @items.length %>)</h4><br>

	<div class="row">
		<% @items.each do |item| %>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading preview">
						<%= image_tag item.photos[0].image.url(:medium) %>
					</div>
					<div class="panel-body">
						<%= link_to item.item_name, item %>
					</div>
				</div>
			</div>
		<% end %>

	</div>
</div>